# Generated by Django 5.2.4 on 2025-12-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toons', '0003_survey_webtoon_surveylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey_webtoon',
            name='genre',
        ),
    ]
